version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  python: circleci/python@1.4.0
  jq: circleci/jq@2.2.0

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7
        auth:
          username: ${DOCKERHUB_USER}
          password: ${DOCKERHUB_PASSWORD}
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: install bundler
          command: gem install bundler
      - run: bundle install --path vendor/bundle
      

  test:
    docker:
      - image: cimg/ruby:2.7
        auth:
          username: ${DOCKERHUB_USER}
          password: ${DOCKERHUB_PASSWORD}      
    steps:
      - checkout
      - ruby/install-deps
      - python/dist
      - jq/install
      - run: pip install csvkit

    



workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
